on:
  push:
    branches:
    - main
#            cp -r ~/Final-Year-Project/frontend/dist/frontend/browser/* /var/www/milan-frontend/
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/Final-Year-Project
            git pull origin main
            next build
